import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/* =====================================================
 Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 ===================================================== */

const sidebars: SidebarsConfig = {
  who_sidebar:[
    { type: 'category'
    , label: 'Who we are'
    , items: [ 'who/team'
             , 'who/contact'
             ],
    },
  ],
  what_sidebar:[
    { type: 'category'
    , label: 'What we do'
    , items: [ 'what/training'
             , 'what/consultancy'
             ],
    },
  ],
  unused_tutorial_sidebar: [
    'intro',
    { type: 'category'
    , label: 'Tutorial'
    , items: ['tutorial-basics/create-a-document'],
    },
  ],
  unused_allpages_sidebar: [
    { type: 'autogenerated'
    , dirName: '.'
    },
  ],
};

export default sidebars;
